# -*- coding: utf-8 -*-
"""DashboardConsoles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ic77mxFv2ADUkEReyXlDgixmPivoiSyl
"""

import json
import pandas as pd
from urllib.request import urlopen
import plotly.express as px

consoles = pd.read_csv('./Console_Data.csv')
df = pd.DataFrame.from_dict(consoles)
df.rename(columns= {'Console Name':'Nome do Console','Units sold (million)':'Unidades Vendidas em Milhão','Company':'Empresa'}, inplace=True)
df

df_vendas = df.groupby('Nome do Console')[['Unidades Vendidas em Milhão']].sum().sort_values('Unidades Vendidas em Milhão', ascending=False)
df_vendas

grafico_vendas = px.bar(
    df_vendas,
    color_discrete_sequence=['mediumslateblue'],
    template='plotly_dark',
    text_auto = True,
    title = "Vendas de Consoles na Historia"
)
grafico_vendas

df_vendas_empresas = df.groupby('Empresa')[['Unidades Vendidas em Milhão']].sum().sort_values('Unidades Vendidas em Milhão', ascending=False)
df_vendas_empresas

grafico_vendas_empresas = px.bar(
    df_vendas_empresas,
    color_discrete_sequence=['mediumslateblue'],
    template='plotly_dark',
    text_auto = True,
    title = "Vendas de Consoles por Empresa na Historia"
)
grafico_vendas_empresas

jogos = pd.read_csv('./scrapped_data.csv')
df_jogos = pd.DataFrame.from_dict(jogos)
df_jogos

df_jogos_console = df_jogos.groupby('System Full')[['Units(m)']].sum().sort_values('Units(m)', ascending=False)
df_jogos_console

grafico_jogos_console = px.bar(
    df_jogos_console,
    color_discrete_sequence=['mediumslateblue'],
    template='plotly_dark',
    text =None,
    title = "Vendas de Jogos por Console"
)
grafico_jogos_console

df_jogos_vendas = df_jogos.groupby('Game Name')[['Units(m)']].sum().sort_values('Units(m)',ascending=False)

grafico_jogos_vendas = px.bar(
    df_jogos_vendas.head(10),
    color_discrete_sequence=['mediumslateblue'],
    template='plotly_dark',
    text =None,
    title = "Jogos Mais Vendidos de Todos os Tempos"
)

grafico_jogos_vendas

df_vendas_gen = df.groupby('Generation')[['Unidades Vendidas em Milhão']].sum().sort_values('Generation',ascending=False)
df_vendas_gen

grafico_vendas_gen = px.bar(
    df_vendas_gen,
    color_discrete_sequence=['mediumslateblue'],
    template='plotly_dark',
    text =None,
    title = "Vendas de Consoles Por Geração"
)

grafico_vendas_gen

df_vendas_pub = df_jogos.groupby('Publisher')[['Units(m)']].sum().sort_values('Units(m)',ascending=False)

grafico_vendas_pub = px.bar(
    df_vendas_pub.head(10),
    color_discrete_sequence=['mediumslateblue'],
    template='plotly_dark',
    text =None,
    title = "Vendas de Jogos por Publicadoraa"
)

grafico_vendas_pub

!pip install -q streamlit

!npm install localtunnel

import urllib
print("SENHA/Enpoint IP para o túnel local:",urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip("\n"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# from prova import *
# 
# st.set_page_config(layout='wide')
# st.title("Dashboard de Console/Jogos :video_game:")
# 
# aba1, aba2, aba3 = st.tabs(['Consoles', 'Jogos', 'Base de Dados'])
# with aba1:
#   coluna1, coluna2 = st.columns(2)
# 
#   with coluna1:
#     st.sidebar.title('Filtro de Console')
#     st.sidebar.title('Filtro de Consoles')
#     filtro_console = st.sidebar.multiselect('Console', df['Nome do Console'].unique(), )
#     if filtro_console:
#       df = df[df['Nome do Console'].isin(filtro_console)]
#     st.plotly_chart(grafico_vendas, use_container_width=True)
#     st.plotly_chart(grafico_vendas_empresas, use_container_width=True)
# 
#   with coluna2:
#     st.plotly_chart(grafico_vendas_gen, use_container_width=True)
# 
# with aba2:
#   coluna1, coluna2 = st.columns(2)
# 
#   with coluna1:
# 
#     filtro_publisher = st.sidebar.multiselect('Publisher', df_jogos['Publisher'].unique(), )
#     if filtro_publisher:
#       df_jogos = df_jogos[df_jogos['Publisher'].isin(filtro_publisher)]
#     st.plotly_chart(grafico_jogos_vendas, use_container_width=True)
#     st.plotly_chart(grafico_jogos_console, use_container_width=True)
# 
#   with coluna2:
#     st.plotly_chart(grafico_vendas_pub, use_container_width=True)
# 
# with aba3:
#   coluna1, coluna2 = st.columns(2)
#   with coluna1:
#     st.dataframe(df)
#   with coluna2:
#     st.dataframe(df_jogos)

!streamlit run app.py &>/content/logs.txt & npx localtunnel --port 8501

